### PR TITLE
Optimize assets.

### PR DESCRIPTION
**Pull request by K0-RR**
Lossless compression.

### CODE REVIEW

**Comment by Azagwen** [comment]
may I ask how you did that ? 👀

**Comment by K0-RR** [comment]
I used [oxipng](https://github.com/shssoichiro/oxipng) - `oxipng -o max -s full -r --fix -t 8 -Z`.

**Comment by K0-RR** [comment]
There is also a Github bot you can use, it's not that efficient but still good enough - [imgbot](https://imgbot.net).

**Comment by Azagwen** [comment]
I'm interested to see if the textures have been visually altered in any way, this sounds interesting 👀

**Comment by Azagwen** [comment]
> I'm interested to see if the textures have been visually altered in any way, this sounds interesting 👀

Okay so I downloaded some of them to check closely, and I'm quite stunned that it didn't alter them at all, I guess PNG contains a lot of unused Data by default 🤔

**Comment by Azagwen** [comment]
I can't seem to be able to merge this, I don't know what happened but it doesn't let me

**Comment by Azagwen** [comment]
managed to do it from desktop

**Pull request merged**
